name = "ExploreFunction"
uuid = "9aae1bbf-cc6e-42e7-8060-1dd26ff0623e"
authors = ["Helmuth Naumer <hnaumer2@illinois.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
